---
substitutions:
  mac_address: ''
  name: ''
  service_uuid: ''

globals:
  - id: ble_connected
    initial_value: 'false'
    restore_value: no
    type: bool

binary_sensor:
  - id: ble_connection
    device_class: connectivity
    lambda: |-
      return id(ble_connected);
    name: Bluetooth
    platform: template

ble_client:
  - id: ${name}
    mac_address: ${mac_address}
    name: Status
    on_connect:
      then:
        - lambda: |-
            id(ble_connected) = true;
            ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            id(ble_connected) = false;
            ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");

esp32_ble_tracker:

# number:
#   - platform: template
#     id: train_speed_slider
#     name: Train Speed Throttle
#     initial_value: 0
#     min_value: 0
#     max_value: 100
#     step: 10
#     mode: SLIDER
#     optimistic: true
#     unit_of_measurement: percent
#     on_value:
#       then:
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 0);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x00]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 10);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x02]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 20);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x04]

#         - if:
#             condition:
#               lambda: |-
#                 return (x == 30);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x06]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 40);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x08]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 50);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x0a]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 60);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x0c]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 70);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x0e]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 80);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x10]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 90);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x12]
#         - if:
#             condition:
#               lambda: |-
#                 return (x == 100);
#             then:
#             - ble_client.ble_write:
#                 characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                 service_uuid: ${service_uuid}
#                 value: [0x00, 0x45, 0x14]

# select:
#   - platform: template
#     name: Conductor Announcement
#     id: train_announcement
#     optimistic: true
#     options:
#       - "Random"
#       - "Fastest Freight"
#       - "Hey There"
#       - "Penna Flyer"
#       - "Ready to Roll"
#       - "Squeaky"
#       - "Water and Fire"
#     initial_option: "Random"
#     on_value:
#           then:
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 0);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x00, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 1);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x05, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 2);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x02, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 3);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x06, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 4);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x01, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 5);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x03, 0x00]
#           - if:
#               condition:
#                 lambda: |-
#                   return (id(train_announcement).active_index() == 6);
#               then:
#                 - ble_client.ble_write:
#                     characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#                     service_uuid: ${service_uuid}
#                     value: [0x00, 0x4d, 0x04, 0x00]

# button:
#   - platform: template
#     id: train_stop
#     name: Stop
#     on_press:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x45, 0x00]

#   - platform: template
#     id: train_forward
#     name: Forward
#     on_press:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x46, 0x01]

#   - platform: template
#     id: train_reverse
#     name: Reverse
#     on_press:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x46, 0x02]

#   - platform: template
#     id: disconnect
#     name: Disconnect Train
#     on_press:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x4b, 0x00, 0x00]

# switch:
#   - platform: template
#     id: train_bell
#     name: Bell
#     optimistic: true
#     turn_on_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x47, 0x01]
#     turn_off_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x47, 0x00]

#   - platform: template
#     id: train_horn
#     name: Horn
#     optimistic: true
#     turn_on_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x48, 0x01]
#     turn_off_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x48, 0x00]

#   - platform: template
#     id: train_lights
#     name: Lights
#     optimistic: true
#     restore_mode: RESTORE_DEFAULT_ON
#     turn_on_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x51, 0x01]
#     turn_off_action:
#       then:
#         - ble_client.ble_write:
#             characteristic_uuid: 08590f7e-db05-467e-8757-72f6faeb13d4
#             service_uuid: ${service_uuid}
#             value: [0x00, 0x51, 0x00]

#   - platform: shutdown
#     name: "Train BLE Client Shutdown"

#   - platform: restart
#     name: "Train BLE Client Restart"
